---
# Copyright 2018 widdix GmbH
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
AWSTemplateFormatVersion: '2010-09-09'
Description: 'State: Client security group, OK'
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
    - Label:
        default: 'Parent Stacks'
      Parameters:
      - ParentVPCStack
Parameters:
  ParentVPCStack:
    Description: 'Stack name of parent VPC stack based on vpc/vpc-*azs.yaml template.'
    Type: String
  ParentClientStack:
    Description: 'Stack name of parent client stack based on state/client-sg.yaml template.'
    Type: String
  ParentKmsKeyStack:
    Description: 'Stack name of parent KMS key stack based on security/kms-key.yaml template (ignored when DBSnapshotIdentifier is set, value used from snapshot).'
    Type: String
    Default: ''
  ParentAuroraStack:
    Description: 'Stack name of parent AuroraDB stack based on security/kms-key.yaml template (ignored when DBSnapshotIdentifier is set, value used from snapshot).'
    Type: String
    Default: ''
  DMSEngineVersion:
    Type: String
    Default: '3.4.2'
  DBStack:
    Type: String
    Default: ''
  DMSInstanceClass:
    Description: 'The instance type of database server (see https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Concepts.DBInstanceClass.html).'
    Type: String
    Default: 'dms.t3.micro'
  SourceDBUsername:
    Type: String
    Default: ''
  SourceDBUserPassword:
    Type: String
    Default: ''
  SourceDBName:
    Type: String
    Default: ''
  SourceDBServer:
    Type: String
    Default: ''
Resources:
  DMSVpcRoleHA: 
    Type: "AWS::IAM::Role"
    #Condition: "NotExistsDMSVPCRole"
    Properties: 
      RoleName: "dms-vpc-role"
      AssumeRolePolicyDocument: 
        Statement: 
        - Effect: Allow
          Principal:
            Service: [dms.amazonaws.com]
          Action: ['sts:AssumeRole']
      Path: /
      ManagedPolicyArns: 
      - "arn:aws:iam::aws:policy/service-role/AmazonDMSVPCManagementRole"
      - "arn:aws:iam::aws:policy/service-role/AmazonDMSCloudWatchLogsRole"
      - "arn:aws:iam::aws:policy/AmazonS3FullAccess"
  DMSSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: "DMS Securiry Group"
      VpcId: {'Fn::ImportValue': !Sub '${ParentVPCStack}-VPC'}
      Tags: 
      - Key: Environment
        Value: Production
  DMSReplicationSubnetGroup:
    Type: AWS::DMS::ReplicationSubnetGroup
    Properties: 
      ReplicationSubnetGroupDescription: "dms replication subnet group"
      ReplicationSubnetGroupIdentifier: "dmsinternalsubnets"
      SubnetIds: !Split [',', {'Fn::ImportValue': !Sub '${ParentVPCStack}-SubnetsPrivate'}]
      Tags: 
      - Key: Environment
        Value: Production
    DependsOn: DMSVpcRoleHA
  DMSReplicationInstance: 
    Type: "AWS::DMS::ReplicationInstance"
    Properties: 
      ReplicationInstanceClass: !Ref DMSInstanceClass
      AllocatedStorage: 30
      EngineVersion: !Ref DMSEngineVersion
      AllowMajorVersionUpgrade: true
      AutoMinorVersionUpgrade: true
      AvailabilityZone: {'Fn::ImportValue': !Sub '${ParentVPCStack}-AZA'}
      KmsKeyId: {'Fn::ImportValue': !Sub '${ParentKmsKeyStack}-KeyArn'}
      MultiAZ: false
      PubliclyAccessible: false
      ReplicationInstanceIdentifier: "harepinst"
      ReplicationSubnetGroupIdentifier: !Ref DMSReplicationSubnetGroup
      Tags: 
      - Key: Environment
        Value: Production
      VpcSecurityGroupIds: 
        - !Ref DMSSecurityGroup
        - {'Fn::ImportValue': !Sub '${ParentClientStack}-DBClientSecurityGroup'}
  AuroraDestinationEndpoint: 
    Type: AWS::DMS::Endpoint
    Properties: 
      EndpointType: target
      EngineName: AURORA
      Password: !Sub 
          - '{{resolve:secretsmanager:${SecretArn}:SecretString:password}}'
          - SecretArn: {'Fn::ImportValue': !Sub '${DBStack}-AuroraInstanceSecret'}
      Port: 3306
      ServerName: {'Fn::ImportValue': !Sub '${ParentAuroraStack}-DNSName'}
      Username: !Sub 
          - '{{resolve:secretsmanager:${SecretArn}:SecretString:username}}'
          - SecretArn: {'Fn::ImportValue': !Sub '${DBStack}-AuroraInstanceSecret'}
    DependsOn: DMSReplicationInstance
  HomeAssistantSourceEndpoint: 
    Type: AWS::DMS::Endpoint
    Properties: 
      EndpointType: source
      EngineName: mysql
      Password: !Ref SourceDBUserPassword
      Port: 3306
      DatabaseName: !Ref SourceDBName
      ServerName: !Ref SourceDBServer
      Username: !Ref SourceDBUsername
    DependsOn: DMSReplicationInstance 
  DMSReplicationTask:
    Type: AWS::DMS::ReplicationTask
    Properties:
      MigrationType: "full-load-and-cdc"
      ReplicationInstanceArn:  !Ref DMSReplicationInstance
      ReplicationTaskSettings: "{ \"Logging\" : { \"EnableLogging\" : true, \"LogComponents\": [ { \"Id\" : \"SOURCE_UNLOAD\", \"Severity\" : \"LOGGER_SEVERITY_DEFAULT\" }, { \"Id\" : \"SOURCE_CAPTURE\", \"Severity\" : \"LOGGER_SEVERITY_DEFAULT\" }, { \"Id\" : \"TARGET_LOAD\", \"Severity\" : \"LOGGER_SEVERITY_DEFAULT\" }, { \"Id\" : \"TARGET_APPLY\", \"Severity\" : \"LOGGER_SEVERITY_DEFAULT\" } ] } }"
      #"{\"Logging\": {\"CloudWatchLogGroup\": \"/aws/dms/tasks/homeassistant-replication\", \"CloudWatchLogStream\": \"dms-task-ha-replication\", \"EnableLogging\": false, \"LogComponents\": [{\"Id\": \"SOURCE_UNLOAD\", \"Severity\": \"LOGGER_SEVERITY_DEFAULT\"}, {\"Id\": \"SOURCE_CAPTURE\", \"Severity\": \"LOGGER_SEVERITY_DEFAULT\"}, {\"Id\": \"TARGET_LOAD\", \"Severity\": \"LOGGER_SEVERITY_DEFAULT\"}, {\"Id\": \"TARGET_APPLY\", \"Severity\": \"LOGGER_SEVERITY_DEFAULT\"}, {\"Id\": \"TASK_MANAGER\", \"Severity\": \"LOGGER_SEVERITY_DEFAULT\"}]}, \"ControlTablesSettings\": {\"SuspendedTablesTableEnabled\": false, \"HistoryTimeslotInMinutes\": 5, \"historyTimeslotInMinutes\": 5, \"StatusTableEnabled\": false, \"HistoryTableEnabled\": false, \"ControlSchema\": \"\"}, \"ChangeProcessingTuning\": {\"BatchApplyTimeoutMax\": 30, \"BatchApplyPreserveTransaction\": true, \"MemoryKeepTime\": 60, \"BatchApplyMemoryLimit\": 500, \"BatchSplitSize\": 0, \"StatementCacheSize\": 50, \"MinTransactionSize\": 1000, \"MemoryLimitTotal\": 1024, \"BatchApplyTimeoutMin\": 1, \"CommitTimeout\": 1}, \"TargetMetadata\": {\"SupportLobs\": false, \"LoadMaxFileSize\": 0, \"LimitedSizeLobMode\": true, \"FullLobMode\": false, \"TargetSchema\": \"\", \"LobMaxSize\": 32, \"ParallelLoadThreads\": 0, \"LobChunkSize\": 64, \"ParallelLoadBufferSize\": 0, \"BatchApplyEnabled\": false}, \"ChangeProcessingDdlHandlingPolicy\": {\"HandleSourceTableTruncated\": true, \"HandleSourceTableAltered\": true, \"HandleSourceTableDropped\": true}, \"FullLoadSettings\": {\"CreatePkAfterFullLoad\": false, \"TargetTablePrepMode\": \"DROP_AND_CREATE\", \"StopTaskCachedChangesApplied\": false, \"TransactionConsistencyTimeout\": 600, \"StopTaskCachedChangesNotApplied\": false, \"MaxFullLoadSubTasks\": 8, \"CommitRate\": 10000}, \"ErrorBehavior\": {\"TableErrorEscalationPolicy\": \"STOP_TASK\", \"RecoverableErrorThrottlingMax\": 1800, \"ApplyErrorDeletePolicy\": \"IGNORE_RECORD\", \"ApplyErrorEscalationPolicy\": \"LOG_ERROR\", \"ApplyErrorUpdatePolicy\": \"LOG_ERROR\", \"DataTruncationErrorPolicy\": \"LOG_ERROR\", \"RecoverableErrorInterval\": 5, \"RecoverableErrorCount\": -1, \"FullLoadIgnoreConflicts\": true, \"DataErrorEscalationPolicy\": \"SUSPEND_TABLE\", \"ApplyErrorInsertPolicy\": \"LOG_ERROR\", \"ApplyErrorEscalationCount\": 0, \"RecoverableErrorThrottling\": true, \"TableErrorEscalationCount\": 0, \"TableErrorPolicy\": \"SUSPEND_TABLE\", \"DataErrorEscalationCount\": 0, \"DataErrorPolicy\": \"LOG_ERROR\"}, \"StreamBufferSettings\": {\"StreamBufferSizeInMB\": 8, \"StreamBufferCount\": 3, \"CtrlStreamBufferSizeInMB\": 5}}"
      SourceEndpointArn: !Ref HomeAssistantSourceEndpoint
      TargetEndpointArn: !Ref AuroraDestinationEndpoint
      TableMappings: "{\"rules\": [{\"rule-type\": \"selection\", \"rule-id\": \"1\", \"rule-action\": \"include\", \"object-locator\": {\"schema-name\": \"mrvhomeassistantdb\", \"table-name\": \"%\"}, \"rule-name\": \"1\"}]}"
    DependsOn:
      - HomeAssistantSourceEndpoint
      - AuroraDestinationEndpoint
      - DMSReplicationInstance
Outputs:
  StackName:
    Description: 'Stack name.'
    Value: !Sub '${AWS::StackName}'
  DMSSecurityGroup:
    Description: 'Use this Security Group to reference client traffic.'
    Value: !Ref DMSSecurityGroup
    Export:
      Name: !Sub '${AWS::StackName}-DMSSecurityGroup'
